# Jaeger-Env

version: "3"
services: 
  jaeger-env:
    image: "jaeger-env:v0.2" 
    ports: 
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
    command: ["./root/boot.sh"]
    environment:
      - SPAN_STORAGE_TYPE=supbagent
    restart: on-failure

  hotrod:
    image: jaegertracing/example-hotrod:latest
    ports:
      - '8080:8080'
      - '8083:8083'
    environment:
      - JAEGER_AGENT_HOST=jaeger-env
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_TYPE=remote
      - JAEGER_SAMPLING_ENDPOINT=http://jaeger-env:5778/sampling
    command: ["-m","prometheus","all"]
    depends_on:
      - jaeger-env

