# docker run --restart=always --network host -d -v /home/docker/frp/frpc.ini:/etc/frp/frpc.ini --name frpc snowdreamtech/frpc

version: "3"
services:
  frpc:
    image: "snowdreamtech/frpc"
    container_name: frpc-minikube
    network_mode: host
    restart: always
    volumes:
      - ./frpc.ini:/etc/frp/frpc.ini

version: "3"
services:
  frpc:
    image: "snowdreamtech/frps:latest"
    container_name: fhl-frps
    network_mode: host
    restart: always
    volumes:
      - ./frps.ini:/etc/frp/frps.ini
    
