apiVersion: v1
kind: ConfigMap
metadata:
  name: frpc-config
  namespace: minikube-frpc
data:
  frpc.ini: |
    [common]
    server_addr = 39.101.140.145
    server_port = 7000
    [prometheus-minikube]
    local_ip = 10.109.226.133
    local_port = 9090
    remote_port = 49998
---
apiVersion: v1
kind: Namespace
metadata:
  name: minikube-frpc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minikube-frpc-deploy
  namespace: minikube-frpc
spec:
  selector:
    matchLabels:
      app: minikube-frpc-app
  replicas: 1
  template:
    metadata:
      name: frpc
      namespace: minikube-frpc
      labels:
        app: minikube-frpc-app
    spec:
      containers:
        - name: frp-client
          image: snowdreamtech/frpc:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /etc/frp/
              name: config
      volumes:
        - name: config
          configMap:
            name: frpc-config
            items:             
            - key: frpc.ini             
              path: frpc.ini
