version: "3"
services:
  jaegertracing:
    image: "jaegertracing/all-in-one:latest"
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    command: ["--query.additional-headers","Access-Control-Allow-Origin:*"]
  hotrod:
    image: "jaegertracing/example-hotrod:latest"
    ports:
      - '8080:8080'
      - '8083:8083'
    environment:
      - JAEGER_AGENT_HOST=jaegertracing
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_TYPE=remote
      - JAEGER_SAMPLING_ENDPOINT=http://jaegertracing:5778/sampling
    command: ["-m","prometheus","all"]
    depends_on:
      - jaegertracing
