version: "3"
services: 
  jaeger-query:
    image: "jaegertracing/jaeger-query"
    ports: 
      - "10032:16686" 
    environment: 
      - "SPAN_STORAGE_TYPE=elasticsearch"
      - "ES_SERVER_URLS=http://39.101.140.145:10030" 
    restart: on-failure

